services:
  
  # ===HDFS===
  namenode:
    image: apache/hadoop:3.5.0
    container_name: namenode
    user: root
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # HDFS
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./docker/hadoop-server/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker/hadoop-server/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./docker/hadoop-server/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
    command:
      - bash
      - -c
      - |
        if [ ! -d /hadoop/dfs/name/current ]; then
          echo "Formatting NameNode..."
          hdfs namenode -format -clusterid finpulse -nonInteractive
        fi
        exec hdfs namenode # hdfs becomes the container's PID 1 (not bash), allow receiving any Unix signals sent to the container
    networks:
      - finpulse-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9870/ > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
      
  datanode-1:
    image: apache/hadoop:3.5.0
    container_name: datanode-1
    user: root
    command: ["hdfs", "datanode"]
    depends_on:
      namenode:
        condition: service_healthy
    volumes:
      - datanode1-data:/hadoop/dfs/data
      - ./docker/hadoop-server/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./docker/hadoop-server/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
      - ./docker/hadoop-server/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties:ro
    networks:
      - finpulse-network

  datanode-2:
    image: apache/hadoop:3.5.0
    container_name: datanode-2
    user: root
    command: ["hdfs", "datanode"]
    depends_on:
      namenode:
        condition: service_healthy
    volumes:
      - datanode2-data:/hadoop/dfs/data
      - ./docker/hadoop-server/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./docker/hadoop-server/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
      - ./docker/hadoop-server/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties:ro
    networks:
      - finpulse-network

  # ===Spark===
  spark-master:
    image: apache/spark:4.0.0
    container_name: spark-master
    user: root
    networks:
      - finpulse-network
    ports:
      - 7077:7077 # Spark master RPC port
      - 8080:8080 # Spark master web UI port
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SPARK_NO_DAEMONIZE=true # run Spark master in the foreground
    volumes:
      - ./docker/hadoop-client:/etc/hadoop/conf
      - ./docker/spark:/opt/spark/conf
      - ./jobs:/opt/spark/work-dir/jobs
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"
    
  spark-worker-1:
    image: apache/spark:4.0.0
    container_name: spark-worker-1
    user: root
    depends_on:
      - spark-master
    networks:
      - finpulse-network
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./docker/hadoop-client:/etc/hadoop/conf
      - ./docker/spark:/opt/spark/conf
      - ./jobs:/opt/spark/work-dir/jobs
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - 2g
      - --webui-port
      - "8081"
  
  spark-worker-2:
    image: apache/spark:4.0.0
    container_name: spark-worker-2
    depends_on:
      - spark-master
    networks:
      - finpulse-network
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./docker/hadoop-client:/etc/hadoop/conf
      - ./docker/spark:/opt/spark/conf
      - ./jobs:/opt/spark/work-dir/jobs
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - 2g
      - --webui-port
      - "8081"

  # ===Kafka===
  kafka:
    image: apache/kafka:4.3.0
    container_name: kafka
    user: "0:0"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=0 
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=INTERNAL://:9094,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9094,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS=kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACOTR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - finpulse-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9094 > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKERCONNECT=kafka:9094
      - SERVER_SERVLET_CONTEXTPATH="/"
    ports:
      - "9001:9000"  # UI on localhost:9001 (9000 is taken by HDFS RPC)
    networks:
      - finpulse-network

  producer:
    image: python:3.11-slim-bullseye
    container_name: producer
    volumes: 
      - ./producers:/opt/producers
      - ./data:/opt/data
    command:
      - bash
      - -c
      - "pip install --no-cache-dir kafka-python==2.0.3 && exec sleep infinity"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - finpulse-network
    restart: unless-stopped

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  kafka-data:

networks:
  finpulse-network:
    driver: bridge