services:
  
  # ===HDFS===
  namenode:
    image: apache/hadoop:3.5.0
    container_name: namenode
    user: root
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # HDFS
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./docker/hadoop-server/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker/hadoop-server/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./docker/hadoop-server/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
    command:
      - bash
      - -c
      - |
        if [ ! -d /hadoop/dfs/name/current ]; then
          echo "Formatting NameNode..."
          hdfs namenode -format -clusterid finpulse -nonInteractive
        fi
        exec hdfs namenode # hdfs becomes the container's PID 1 (not bash), allow receiving any Unix signals sent to the container
    networks:
      - finpulse-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9870/ > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
      
  datanode-1:
    image: apache/hadoop:3.5.0
    container_name: datanode-1
    user: root
    command: ["hdfs", "datanode"]
    depends_on:
      namenode:
        condition: service_healthy
    volumes:
      - datanode1-data:/hadoop/dfs/data
      - ./docker/hadoop-server/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./docker/hadoop-server/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
      - ./docker/hadoop-server/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties:ro
    networks:
      - finpulse-network

  datanode-2:
    image: apache/hadoop:3.5.0
    container_name: datanode-2
    user: root
    command: ["hdfs", "datanode"]
    depends_on:
      namenode:
        condition: service_healthy
    volumes:
      - datanode2-data:/hadoop/dfs/data
      - ./docker/hadoop-server/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./docker/hadoop-server/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
      - ./docker/hadoop-server/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties:ro
    networks:
      - finpulse-network

  # ===Spark===
  spark-master:
    image: apache/spark:4.0.0
    container_name: spark-master
    user: root
    networks:
      - finpulse-network
    ports:
      - 7077:7077 # Spark master RPC port
      - 8080:8080 # Spark master web UI port
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SPARK_NO_DAEMONIZE=true # run Spark master in the foreground
    volumes:
      - ./docker/hadoop-client:/etc/hadoop/conf
      - ./docker/spark:/opt/spark/conf
      - ./jobs:/opt/spark/work-dir/jobs
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"
    
  spark-worker-1:
    image: apache/spark:4.0.0
    container_name: spark-worker-1
    user: root
    depends_on:
      - spark-master
    networks:
      - finpulse-network
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./docker/hadoop-client:/etc/hadoop/conf
      - ./docker/spark:/opt/spark/conf
      - ./jobs:/opt/spark/work-dir/jobs
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - 2g
      - --webui-port
      - "8081"
  
  spark-worker-2:
    image: apache/spark:4.0.0
    container_name: spark-worker-2
    depends_on:
      - spark-master
    networks:
      - finpulse-network
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./docker/hadoop-client:/etc/hadoop/conf
      - ./docker/spark:/opt/spark/conf
      - ./jobs:/opt/spark/work-dir/jobs
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - 2g
      - --webui-port
      - "8081"

  # ===Kafka===


volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:


networks:
  finpulse-network:
    driver: bridge