# single node config (coordinator + worker), enough for a development environment
coordinator=true
# works as both coordinator and worker
node-scheduler.include-coordinator=true
# port for the HTTP server
http-server.http.port=8080
# a discovery service that is used by all the nodes to find each other, each node has one
discovery.uri=http://localhost:8080

# IMPORTANT: max-memory-per-node + heap-headroom-per-node < maximum heap size in the JVM on the node (configured in jvm.config)
# heap-headroom-per-node defaults to 30% of heap (~300 MB), so max-memory-per-node must be below ~700 MB
# the max amount of user memory a query can use across the entire cluster
query.max-memory=512MB
# max amount of user memory a query can use on a worker
query.max-memory-per-node=512MB